export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'About',
  headLine: 'Profile',
  description: 'I am a Computer Science student at Memorial University of Newfoundland. I am an enthusiatic individual with attention to detail and excellent organizational skills. Motivated to learn, grow and excel in the software industry.',
  buttonLabel: '',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'Coder',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'resume',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Resume',
  headLine: 'Skills and Qualifications',
  description: `Python, Java, JavaScript, React, HTML5 & CSS3.\n Data Structures, Data Management, Artificial Intelligence and Web Development. Feel free to download my resume for more details`,
  buttonLabel: 'Download Resume',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'Profile',
  dark: false,
  primary: false,
  darkText: true,
  linkto: "//www.drive.google.com/uc?export=download&id=1DpRZgAVUHKLMwVvscC7DexcPe3EpcyS7"
};

// export const homeObjThree = {
//   id: 'contact',
//   lightBg: true,
//   lightText: false,
//   lightTextDesc: false,
//   topLine: 'Contact',
//   headLine: "Let's Talk",
//   description: 'Get access to our exclusive app',
//   buttonLabel: 'Contact Me',
//   imgStart: false,
//   img: require('../../images/svg-3.svg').default,
//   alt: 'Profile',
//   dark: false,
//   primary: false,
//   darkText: true,
// };